// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzJPveJkGzemivhPYfTgq73T5gqDq2yKE',
    appId: '1:521345334447:web:0707f8d081b3cbeda8a85a',
    messagingSenderId: '521345334447',
    projectId: 'auvnet-internship-assess-9a3a6',
    authDomain: 'auvnet-internship-assess-9a3a6.firebaseapp.com',
    storageBucket: 'auvnet-internship-assess-9a3a6.firebasestorage.app',
    measurementId: 'G-WT5QDN97BE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeY1CAkrz4Ud0UyXEwaBF2YPKfc_lBV3Y',
    appId: '1:521345334447:android:2855e47ba0d0b943a8a85a',
    messagingSenderId: '521345334447',
    projectId: 'auvnet-internship-assess-9a3a6',
    storageBucket: 'auvnet-internship-assess-9a3a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxS9Yczu51khWAH9XdpBsKPpTcoAqqL-M',
    appId: '1:521345334447:ios:248cfed85afb1ea5a8a85a',
    messagingSenderId: '521345334447',
    projectId: 'auvnet-internship-assess-9a3a6',
    storageBucket: 'auvnet-internship-assess-9a3a6.firebasestorage.app',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxS9Yczu51khWAH9XdpBsKPpTcoAqqL-M',
    appId: '1:521345334447:ios:248cfed85afb1ea5a8a85a',
    messagingSenderId: '521345334447',
    projectId: 'auvnet-internship-assess-9a3a6',
    storageBucket: 'auvnet-internship-assess-9a3a6.firebasestorage.app',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzJPveJkGzemivhPYfTgq73T5gqDq2yKE',
    appId: '1:521345334447:web:3f53b0de2ac8a521a8a85a',
    messagingSenderId: '521345334447',
    projectId: 'auvnet-internship-assess-9a3a6',
    authDomain: 'auvnet-internship-assess-9a3a6.firebaseapp.com',
    storageBucket: 'auvnet-internship-assess-9a3a6.firebasestorage.app',
    measurementId: 'G-DXTDJ1VN7N',
  );
}
